[package]
name = "swisseph-sys"
version = "0.2.0"
links = "swisseph"
build = "build.rs"
edition = "2021"
authors = ["Sawfan <sawfan@sawfan.com>"]
description = "Rust system wrapper for swisseph C library"
repository = "https://github.com/sawfan/libswisseph-sys_rs"
license = "AGPL-3.0-only"
keywords = ["ephemeris", "astronomy", "astrology"]
exclude = [
    "libswisseph/doc",
    "libswisseph/windows",
    "libswisseph/contrib",
    "libswisseph/ephe",
    "libswisseph/test",
]

[features]
default = []
vfs = []
wasi = []

[build-dependencies]
cc = { version = "1.0.43", features = ["parallel"] }
pkg-config = "0.3.15"

